### ISSUE TITLE
Redireccionamiento de blog

### ISSUE THREAD

**Issue by digitalh** [EnjambreBit/website#1]
El blog antes estaba en enjambrebit.com.ar/blog y ahora está en blog.enjambre.com.ar. Hay posts publicados en las redes sociales que apuntan al viejo blog, por lo que es necesario redirigirlos al nuevo dominio.
Por ejemplo: http://enjambrebit.com.ar/blog/creando-un-servidor-de-aplicaciones-con-dokku/ tiene que ir a http://blog.enjambrelab.com.ar/creando-un-servidor-de-aplicaciones-con-dokku/

**Comment by hugoruscitti** [comment]
Pienso que podríamos hacer un redireccionador similar al que usamos para que la url:  "http://enjambrebit.com.ar/blog/" ahora apunte a "http://blog.enjambrebit.com.ar" @digitalh .

Se que es un poco laborioso, pero me parece que una forma de lograrlo es creando los direccionadores como archivos html. Por ejemplo, las url viejas van a caer en este directorio del repositorio nuevo:

https://github.com/EnjambreBit/website/tree/master/public/blog

el archivo "index.html" es el que se encarga de redireccionar la url "enjambrebit.com.ar/blog" al blog nuevo.

Si queremos redireccionar otra página, como "http://enjambrebit.com.ar/blog/creando-un-servidor-de-aplicaciones-con-dokku/" tendríamos que crear un directorio llamado "creando-un-servidor-de-aplicaciones-con-dokku" con un archivo index.html que contenga la url al artículo nuevo (o sea http://blog.enjambrelab.com.ar/creando-un-servidor-de-aplicaciones-con-dokku/)

Insisto, es medio embole... pero creo que es rápido de hacer considerando que tenemos 3 o 4 url que migrar.

**Comment by hugoruscitti** [comment]
Listo, también hice un release para que se pueda comprobar.

Por ejemplo, por tomar un caso, la URL vieja:

http://enjambrebit.com.ar/blog/resena-del-proyecto-indexar-com-ar/

redirecciona automáticamente a la nueva web:

http://blog.enjambrelab.com.ar/resena-del-proyecto-indexar-com-ar/
